app/mod_catalog/controllers.py
from flask import Blueprint, request, render_template, \
    flash, g, session, redirect, url_for, abort
from sqlalchemy import and_
from app import app
from app import db_session
from app import login_manager
from flask_login import login_required, current_user
from app.mod_auth.models import User
from app.mod_catalog.models import Item, Category
from app.mod_catalog.helpers import render_new_item_page, check_item_creator


mod_catalog = Blueprint('catalog', __name__, url_prefix='/catalog')


@mod_catalog.route('/')
def home():
    """Show list of categories and a list of the latest items
    """
    top_items = db_session.query(Item).order_by(
        Item.created_at.desc()).limit(10).all()
    return render_template('home.html.j2', top_items=top_items)


@mod_catalog.route('/<category_name>')
@mod_catalog.route('/<category_name>/items')
def items_by_category(category_name):
    """Retrieves all items in a specific category

    Args:
        category_name: String, name of category
    """
    category = Category.by_name(category_name)
    if not category:
        return "Error, no category found", 404
    items = Item.by_category(category)
    return render_template("category_items.html.j2",
                            category_name=category.name, items=items)


@mod_catalog.route('/<category_name>/<item_title>')
def get_item(category_name, item_title):
    """Retrieves a specific individual item

    Checks item exists with given category. Pass item to template, returns view
    Args:
        category_name: String, name of category
        item_title: String, title of item
    """
    category = Category.by_name(category_name)
    if not category:
        return "Error, no category found", 404
    item = db_session.query(Item).filter(
        and_(Item.title == item_title, Item.category == category)).first()
    if not item:
        return "Error, no item found", 404

    return render_template('item_view.html.j2', item=item)


@mod_catalog.route('/items/new', methods=['GET', 'POST'])
@login_required
def new_item():
    """Handles creating new catalog item

    GET request returns form for creating item.
    POST request takes data from form and creates a new Item in database with
    given data.
    """
    if request.method == 'GET':
        return render_new_item_page()

    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        category_id = request.form['category_id_inp']

        if not title or not description or not category_id:
            flash("Missing input")
            return render_new_item_page(title, description, category_id)

        category = Category.by_id(category_id)

        if Item.by_title(title):
            flash("Item with title \"%s\" already exists." % title)
            return render_new_item_page(title, description, category_id)

        item = Item(title=title, description=description,
                    category_id=category_id, creator_id=current_user.id)
        db_session.add(item)
        db_session.commit()
        return redirect(url_for('catalog.get_item',
                                category_name=item.category.name,
                                item_title=item.title))


@mod_catalog.route('/<item_title>/edit', methods=['GET', 'POST'])
@login_required
def edit_item(item_title):
        """Handles editing catalog item

        GET returns form for editing given item (pre-filled with current data)
        POST request takes data from form and a updates Item in database with
        given data.

        Args:
            item_title: String, title of item to edit
        """
    # Check item exists and current user is authorized to edit it
    item = Item.by_title(item_title)
    check_item_creator(item) # 403 error if current user != item creator

    if request.method == 'GET':
        return render_new_item_page(item.title, item.description,
                                    item.category_id)
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        category_id = request.form['category_id_inp']
        if not title or not description or not category_id:
            flash("Missing input")
            return render_new_item_page(title, description, category_id)
        item.title = title
        item.description = description
        itme.category_id = category_id
        db_session.add(item)
        db_session.commit()
        return redirect(url_for('catalog.get_item',
                                category_name=item.category.name,
                                item_title=item.title))


@mod_catalog.route('/<item_title>/delete', methods=['GET', 'POST'])
@login_required
def delete_item(item_title):
    """Handles deleting catalog item

    GET returns confirmation page for deleting item.
    POST request removes item from database, then redirect to homepage.

    Args:
        item_title: String, title of item to delete
    """
    item = Item.by_title(item_title)
    check_item_creator(item)
    if request.method == 'GET':
        return render_template('delete_item.html.j2', item=item)
    if request.method == 'POST':
        db_session.delete(item)
        db_session.commit()
        flash("%s successfully deleted" % item_title)
        return redirect(url_for('catalog.home'))

app/templates/base.html.j2
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome CDN -->
    <script src="https://use.fontawesome.com/488e44b3c7.js"></script>
    <!-- Foundation Styles -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/foundation.min.css')}}">
    <!-- Roboto Font for gsignin button -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:500" rel="stylesheet">
    <!-- Custom styles -->
    <link rel="stylesheet" href="{{url_for('static',filename='css/app.css')}}">
    <title>Catalog App</title>
  </head>
  <body>

      {%include "partials/categories_offcanvas.html.j2"%}
      <div class="off-canvas-content">
        {% include "partials/header.html.j2" %}
        <br>
        {% with messages = get_flashed_messages() %}
          {% if messages %}
          <div class="row">
            <div class="columns">
              {% for message in messages %}
              <div class="callout success">
                {{ message }}
              </div>
              {% endfor %}
            </div>
          </div>
          {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock %}
      </div>

    <!-- Foundation/Jquery JS -->
    <script src="{{url_for('static', filename='js/vendor/jquery.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/what-input.js')}}"></script>
    <script src="{{url_for('static', filename='js/vendor/foundation.min.js')}}"></script>
      <script src="{{url_for('static', filename='js/app.js')}}"></script>
    <script>
      $(document).foundation();
   </script>
  </body>
</html>

app/templates/category_items.html.j2
{% extends "base.html.j2" %}
{% block content %}
<div class="row">
  <div class="small-2 medium-4 columns category-list">
    {%include 'category_list.html.j2'%}
  </div>
  <div class="small-8 medium-8 columns">
    <div class="category-items">
      <h1>{{category_name}}</h1>
      {% if items %}
        <ul class="no-bullet">
          {% for item in items %}
            <li>
              <a href="{{url_for('catalog.get_item', category_name=item.category.name, item_title=item.title)}}">
                {{item.title}}
              </a>
            </li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

app/templates/category_list.html.j2
  <h2>Categories</h2>
  <ul class="no-bullet">
    {%for category in categories%}
      <li>
        <a href="{{url_for('catalog.items_by_category', category_name=category.name)}}">
          {{category.name}}
        </a>
      </li>
    {%endfor%}
  </ul>

app/templates/delete_item.html.j2
{% extends "base.html.j2" %}

{% block content %}
<div class="row">
  <div class="small-2 medium-4 columns category-list">
    {%include 'category_list.html.j2'%}
  </div>
  <div class="columns">
    <h1>Delete Item</h1>
    <p>
      Are you sure you want to delete <strong>{{item.title}}</strong>
      from the catalog?
    </p>
    <form action="" method="post">
      <input class= "button alert" type="submit" value="Delete">
      <a href="{{url_for('catalog.get_item', category_name=item.category.name, item_title=item.title)}}" class="button primary">
        Cancel
      </a>
    </form>

  </div>

</div>



{% endblock %}

app/templates/home.html.j2
{% extends "base.html.j2" %}
{% block content %}
  <!-- {% with messages = get_flashed_messages() %}
    {% if messages %}
      <ul class=flashes>
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
      </ul>
    {% endif %}
  {% endwith %} -->
  <div class="row">
    <div class="small-2 medium-4 columns category-list">
      {%include 'category_list.html.j2'%}
    </div>

    <div class="small-8 medium-8 columns">
      <div class="latest-items">
        <h1>Latest Items</h1>
        <ul class="no-bullet ">
          {% for item in top_items %}
            <li>
              <a href="{{url_for('catalog.get_item', category_name=item.category.name, item_title=item.title)}}">
                {{item.title}}
              </a>
              <a class="subheader" href="{{url_for('catalog.items_by_category',category_name=item.category.name)}}">
              ({{item.category.name}})
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

{% endblock %}

app/templates/item_view.html.j2
{% extends "base.html.j2" %}
{% block content %}
  <div class="row">
    <div class="small-2 medium-4 columns category-list">
      {%include 'category_list.html.j2'%}
    </div>
    <div class="columns">
      <h1>{{item.title}}</h1>
      <hr>
      <p><strong>Description: </strong>{{item.description}}</p>
    </div>
  </div>
  <div class="row">
    <div class="columns">
      {% if current_user.is_authenticated and item.user == current_user%}
        <a class="button primary" href="{{url_for('catalog.edit_item', item_title=item.title)}}">Edit</a>
        <a class="button alert"  href="{{url_for('catalog.delete_item', item_title=item.title)}}">Delete</a>
      {% endif %}
    </div>
  </div>
{% endblock %}

app/templates/new_edit_item.html.j2
{% extends "base.html.j2" %}
{% block content %}


<div class="row">
  <div class="small-2 medium-4 columns category-list">
    {%include 'category_list.html.j2'%}
  </div>
  <div class="columns">
    <h1>{{page_heading}}</h1>
    <form class="form-create-item"action="{{url_for('catalog.new_item')}}" method="post">
      <div class="row">
        <div class="medium-6 small-12 columns">
          <label for="titleInput">Title</label>
          <input type="text" id="titleInput" name="title" value="{{title}}">
        </div>
        <div class= "medium-6 small-12 columns">
          <label for="categoryInput">Category</label>
          <select name='category_id_inp' id="categoryInput">
            <option value="" disabled selected>Select a category</option>
            {% for i in categories %}
            <option value="{{i.id}}" {% if i.id==category_id %} selected="selected" {% endif %}>{{i.name}}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="row columns">
        <label for="descriptionInput">Description</label>
        <textarea name="description" id="descriptionInput">{{description}}</textarea>
      </div>
      <div class="button-container text-center">
        <button class="button primary" type="submit" name="button">Submit</button>
        <a href="{{url_for('catalog.home')}}" class="button secondary">
          Cancel
        </a>
      </div>
    </form>
  </div>
</div>

{% endblock %}

app/templates/new_item.html.j2
<h1>Create Item</h1>

<form action="{{url_for('catalog.new_item')}}" method="post">
  <div>
    <label for="titleInput">Title</label>
    <br>
    <input type="text" id="titleInput" name="title" value="{{title}}">
  </div>
  <br>
  <div>
    <label for="descriptionInput">Description</label>
    <br>
    <textarea name="description" id="descriptionInput">{{description}}</textarea>
  </div>
  <br>
  <div >
    <label for="categoryInput">Category</label>
    <br>
    <select name='category_id_inp' id="categoryInput">
      <option value="" disabled selected>Select a category</option>
      {% for i in categories %}
      <option value="{{i.id}}" {% if i.id==category_id %} selected="selected" {% endif %}>{{i.name}}</option>
      {% endfor %}
    </select>
  </div>
  <br>
  <button type="submit" name="button">Submit</button>
</form>